### ISSUE TITLE
jars not properly loaded on windows (rhino)

### ISSUE THREAD

**Issue by tschaub** [280north/narwhal#2]
The packages module for the rhino engine constructs a URL for jars by prepending jar paths with "file://".  This doesn't work on Windows with absolute paths.

Kris Zyp's commit [here](http://github.com/kriszyp/narwhal/commit/750eb21361f1299cabb63a5c3f592dbb06f8557b) is meant to solve the same issue.

This can also be fixed by using `file.toURL`.

**Comment by tschaub** [comment]
Word is that http://github.com/tschaub/narwhal/commit/68c272e28e39fa68d6eca71d62df9df53ef26181 works for Kris as well.

**Comment by tlrobinson** [comment]
SHA: 3eee984238eeb930f0e5027479e82ecf7279bd52
